spring.application.name=exercise

# Konfigurasi Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/excercise
spring.datasource.username=postgres
spring.datasource.password=titosetiawan
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfigurasi Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true